---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: af94300e28b55fc3ca63ba6d7269b4edf745e403
    app.quarkus.io/build-timestamp: 2023-03-26 - 15:12:01 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: demo-remote-dev
  name: demo-remote-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: demo-remote-dev
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: af94300e28b55fc3ca63ba6d7269b4edf745e403
        app.quarkus.io/build-timestamp: 2023-03-26 - 15:12:01 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: demo-remote-dev
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_LAUNCH_DEVMODE
              value: "true"
          image: localhost:32000/bratuhia/demo-remote-dev:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: demo-remote-dev
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: af94300e28b55fc3ca63ba6d7269b4edf745e403
    app.quarkus.io/build-timestamp: 2023-03-26 - 15:12:01 +0000
  labels:
    app.kubernetes.io/name: demo-remote-dev
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: demo-remote-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: demo-remote-dev
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
